name: Build IPA

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app
        
      - name: Install needed tools
        run: |
          brew install ldid dpkg
          
      - name: Build & Sign Application
        run: |
          make
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Antoine-IPA
          path: ${{ github.workspace }}/build/Antoine.ipa
          
      - name: Upload deb for Jailbroken devices
        uses: actions/upload-artifact@v4
        with:
          name: Antoine
          path: ${{ github.workspace }}/build/Antoine.deb
